#!/bin/bash
chmod 0700 ~/.ssh
chmod 0644 ~/.ssh/* # authorized_keys,config,*.pub and anything else
chmod 0600 ~/.ssh/*_rsa
mkdir -p ~/.ssh/multiplex
chmod 0755 ~/.ssh/multiplex

# cheat paths
mkdir -p ~/.cheat/community ~/.cheat/work/ ~/.cheat/personal

if grep -qEi '(microsoft|wsl)' /proc/version; then
	APPDATA_DIR=$(wslpath $(wslvar APPDATA))
	# copy alacritty config to windows path
	ALACRITTY_PATH="$APPDATA_DIR/alacritty"
	mkdir -p "$ALACRITTY_PATH"
	rm -f "$ALACRITTY_PATH/alacritty.yml"
	cp -f ~/.config/alacritty/alacritty.yml "$ALACRITTY_PATH/"

	# autostart things
	STARTUP_PATH="$APPDATA_DIR/Microsoft/Windows/Start Menu/Programs/Startup"
	cp -f ../extra-settings/keybindings.ahk "$STARTUP_PATH/keybindings.ahk"
	cp -f ../extra-settings/launch-vcxsrv.lnk "$STARTUP_PATH/vcxsrv.lnk"
fi
