import = ["~/.config/alacritty/base.toml"]

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args    = ["-c", "tmux new-session -As 0 || tmux attach-session -d"]

[font]
size = 12.0

[window]
decorations    = "full"
option_as_alt  = "OnlyLeft"

[[hints.enabled]]
command      = "open"
hyperlinks   = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key  = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods    = "None"
